//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teram.Module.Authentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationSharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationSharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teram.Module.Authentication.Resources.AuthenticationSharedResource", typeof(AuthenticationSharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازنشانی گذرواژه باید یک کد ارائه شود..
        /// </summary>
        public static string A_code_must_be_supplied_for_password_reset_ {
            get {
                return ResourceManager.GetString("A code must be supplied for password reset.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به صفحه اصلی.
        /// </summary>
        public static string Back_Home {
            get {
                return ResourceManager.GetString("Back Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام در سامانه ارتباط با تامین کنندگان.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری کلمه عبور یا Captcha را کنترل نمایید.
        /// </summary>
        public static string Error_In_Login {
            get {
                return ResourceManager.GetString("Error In Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا ثبت نام کرده ام..
        /// </summary>
        public static string ExistAccount {
            get {
                return ResourceManager.GetString("ExistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوقی.
        /// </summary>
        public static string Legal_Person {
            get {
                return ResourceManager.GetString("Legal Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه ارتباط با تامین کنندگان.
        /// </summary>
        public static string LoginSamane {
            get {
                return ResourceManager.GetString("LoginSamane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات درست وارد نشده است.
        /// </summary>
        public static string Model_State_Error {
            get {
                return ResourceManager.GetString("Model State Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی / شناسه ملی.
        /// </summary>
        public static string National_Code {
            get {
                return ResourceManager.GetString("National Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از کاراکترهای فارسی در کلمه عبور مجاز نیست..
        /// </summary>
        public static string Note_Fifth {
            get {
                return ResourceManager.GetString("Note Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت نام نوع شخص حقیقی یا حقوقی را تعیین کنید..
        /// </summary>
        public static string Note_First {
            get {
                return ResourceManager.GetString("Note First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبورانتخابی حداقل 8 کاراکتر و ترکیبی از اعداد،حروف بزرگ،حروف کوچک و کاراکترهای ویژه می باشد..
        /// </summary>
        public static string Note_Fourth {
            get {
                return ResourceManager.GetString("Note Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای اشخاص حقیقی کد ملی و برای اشخاص حقوقی شناسه ی ملی به عنوان نام کاربری الزامی می باشد..
        /// </summary>
        public static string Note_Second {
            get {
                return ResourceManager.GetString("Note Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه ی آدرس ایمیل جهت دریافت کد تایید الزامی است..
        /// </summary>
        public static string Note_Third {
            get {
                return ResourceManager.GetString("Note Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا قبل از ثبت نام به نکات زیر توجه کنید:.
        /// </summary>
        public static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور فعلی.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول وارد شده برای رمز عبور 11 کاراکتر می باشد..
        /// </summary>
        public static string Password_Max_Length_Error {
            get {
                return ResourceManager.GetString("Password Max Length Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول رمز عبور کمتر از مقدار تعریف شده می باشد..
        /// </summary>
        public static string Password_Min_Length_Error {
            get {
                return ResourceManager.GetString("Password Min Length Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد ها با هم تطابق ندارند..
        /// </summary>
        public static string Password_mismatch {
            get {
                return ResourceManager.GetString("Password mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع شخص:.
        /// </summary>
        public static string Person_Type {
            get {
                return ResourceManager.GetString("Person Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل با فرمت درست وارد نمایید!.
        /// </summary>
        public static string Please_enter_a_valid_email_address_ {
            get {
                return ResourceManager.GetString("Please enter a valid email address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل صحیح وارد نمایید!.
        /// </summary>
        public static string Please_enter_correct_Email {
            get {
                return ResourceManager.GetString("Please enter correct Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام کاربری ، کد ملی معتبر وارد نمایید..
        /// </summary>
        public static string Please_enter_valid_National_Code_as_User_Name {
            get {
                return ResourceManager.GetString("Please enter valid National Code as User Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور ترکیبی از اعداد،حروف بزرگ،حروف کوچک و کاراکترهای ویژه می باشد..
        /// </summary>
        public static string Please_enter_valid_Password {
            get {
                return ResourceManager.GetString("Please enter valid Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری شامل کاراکترهای انگلیسی و اعداد می تواند باشد..
        /// </summary>
        public static string Please_enter_valid_UserName {
            get {
                return ResourceManager.GetString("Please enter valid UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی برای اشخاص حقیقی 10 کاراکتر و برای اشخاص حقوقی 11 کاراکتر می باشد، ثبت اطلاعات امکان پذیر نیست.
        /// </summary>
        public static string Please_neter_valid_national_code_for_real_and_legal_person {
            get {
                return ResourceManager.GetString("Please neter valid national code for real and legal person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقیقی.
        /// </summary>
        public static string Real_Person {
            get {
                return ResourceManager.GetString("Real Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام .
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با موفقیت انجام شد ،لطفا برای فعال سازی حساب کاربری خود صندوق پست الکترونیکی خود را بررسی نمایید.
        /// </summary>
        public static string Successfully_addedd_Please_check_your_email_to_confirm_your_account_ {
            get {
                return ResourceManager.GetString("Successfully addedd,Please check your email to confirm your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل را وارد نمایید!.
        /// </summary>
        public static string The_field_Email_is_required {
            get {
                return ResourceManager.GetString("The field Email is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول وارد شده برای ایمیل 100 کاراکتر می باشد..
        /// </summary>
        public static string The_field_Email_must_be_a_string_or_array_type_with_a_maximum_length_of__100__ {
            get {
                return ResourceManager.GetString("The field Email must be a string or array type with a maximum length of \'100\'.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی برای اشخاص حقیقی 10 کاراکتر و برای اشخاص حقوقی 11 کاراکتر می باشد..
        /// </summary>
        public static string The_field_National_Code_must_be_a_string_or_array_type_with_a_maximum_length_of__11__ {
            get {
                return ResourceManager.GetString("The field National Code must be a string or array type with a maximum length of \'" +
                        "11\'.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی برای اشخاص حقیقی 10 کاراکتر و برای اشخاص حقوقی 11 کاراکتر می باشد..
        /// </summary>
        public static string The_field_National_Code_must_be_a_string_or_array_type_with_a_minimum_length_of__10__ {
            get {
                return ResourceManager.GetString("The field National Code must be a string or array type with a minimum length of \'" +
                        "10\'.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد ملی را وارد نمایید!.
        /// </summary>
        public static string The_field_NationalCode_is_required {
            get {
                return ResourceManager.GetString("The field NationalCode is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا رمز عبور را وارد نمایید!.
        /// </summary>
        public static string The_field_Password_is_required {
            get {
                return ResourceManager.GetString("The field Password is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فیلد نوع شخص را انتخاب نمایید!.
        /// </summary>
        public static string The_field_PersonType_is_required {
            get {
                return ResourceManager.GetString("The field PersonType is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری برای اشخاص حقیقی 10 کاراکتر و برای اشخاص حقوقی 11 کاراکتر می باشد..
        /// </summary>
        public static string The_field_User_Name_must_be_a_string_or_array_type_with_a_maximum_length_of__11__1 {
            get {
                return ResourceManager.GetString("The field User Name must be a string or array type with a maximum length of \'11\'." +
                        "1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری برای اشخاص حقیقی 10 کاراکتر و برای اشخاص حقوقی 11 کاراکتر می باشد..
        /// </summary>
        public static string The_field_User_Name_must_be_a_string_or_array_type_with_a_minimum_length_of__10__1 {
            get {
                return ResourceManager.GetString("The field User Name must be a string or array type with a minimum length of \'10\'." +
                        "1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام کاربری را وارد نمایید.
        /// </summary>
        public static string The_field_UserName_is_required {
            get {
                return ResourceManager.GetString("The field UserName is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر جدید به همراه یک پسورد جدید ایجاد شده است. .
        /// </summary>
        public static string User_created_a_new_account_with_password_ {
            get {
                return ResourceManager.GetString("User created a new account with password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
