// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teram.HR.Module.Recruitment.Entities.DbContext;

#nullable disable

namespace Teram.HR.Module.Recruitment.Migrations
{
    [DbContext(typeof(HRContext))]
    [Migration("20231021060445_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants", b =>
                {
                    b.Property<int>("JobApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicantId"));

                    b.Property<int>("NationalCode")
                        .HasColumnType("int");

                    b.HasKey("JobApplicantId");

                    b.ToTable("JobApplicants", "HR");
                });
#pragma warning restore 612, 618
        }
    }
}
