// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teram.HR.Module.Recruitment.Entities.DbContext;

#nullable disable

namespace Teram.HR.Module.Recruitment.Migrations
{
    [DbContext(typeof(HRContext))]
    [Migration("20231104071052_AddWorkWithUsTables")]
    partial class AddWorkWithUsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.BaseInfo.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MajorId");

                    b.ToTable("Majors", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", b =>
                {
                    b.Property<int>("JobApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificateNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BirthCertificateSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenderType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("decimal(18,15)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobApplicantId");

                    b.HasIndex("MajorId");

                    b.HasIndex("NationalCode", "Email")
                        .IsUnique();

                    b.ToTable("JobApplicants", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicantFile", b =>
                {
                    b.Property<int>("JobApplicantFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicantFileId"));

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobApplicantId")
                        .HasColumnType("int");

                    b.HasKey("JobApplicantFileId");

                    b.HasIndex("JobApplicantId");

                    b.ToTable("JobApplicantFiles", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.PersonQuestionnaireQuestion", b =>
                {
                    b.Property<int>("PersonQuestionnaireQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonQuestionnaireQuestionId"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonnelQuestionnaireId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionnaireQuestionId")
                        .HasColumnType("int");

                    b.HasKey("PersonQuestionnaireQuestionId");

                    b.HasIndex("PersonnelQuestionnaireId");

                    b.HasIndex("QuestionnaireQuestionId");

                    b.ToTable("PersonQuestionnaireQuestions", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.PersonnelQuestionnaire", b =>
                {
                    b.Property<int>("PersonnelQuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonnelQuestionnaireId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonnelQuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("PersonnelQuestionnaires", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.Questionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionnaireId");

                    b.ToTable("Questionnaires", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.QuestionnaireQuestion", b =>
                {
                    b.Property<int>("QuestionnaireQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireQuestionId"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int");

                    b.HasKey("QuestionnaireQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireQuestions", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.BaseInformation", b =>
                {
                    b.Property<int>("BaseInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaseInformationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirthLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<bool>("BusinessMissionAbility")
                        .HasColumnType("bit");

                    b.Property<bool>("CanWorkInShifts")
                        .HasColumnType("bit");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriminalRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDateMilitaryService")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeTimeActivities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("HasCriminalRecord")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIntentionToMigrate")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpecialDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWorkingRelatives")
                        .HasColumnType("bit");

                    b.Property<int?>("HomeCityId")
                        .HasColumnType("int");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentitySerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsuranceMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,15)");

                    b.Property<int>("MarriageStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MilitaryServiceCityId")
                        .HasColumnType("int");

                    b.Property<int?>("MilitaryServiceStatus")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PartnerEducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("PartnerJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadyToWorkDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Religion")
                        .HasColumnType("int");

                    b.Property<double?>("RequiredSalary")
                        .HasColumnType("float");

                    b.Property<string>("Sect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialAcademicAchievements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialDisease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialWorkSuccesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDateMilitaryService")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThesisTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitOfmilitaryService")
                        .HasColumnType("int");

                    b.Property<string>("WorkingRelatives")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BaseInformationId");

                    b.ToTable("BaseInformation", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<int>("BaseInformationId")
                        .HasColumnType("int");

                    b.Property<int>("EducationDurationHour")
                        .HasColumnType("int");

                    b.Property<int>("EducationYear")
                        .HasColumnType("int");

                    b.Property<bool>("HasCertificate")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationId");

                    b.HasIndex("BaseInformationId");

                    b.ToTable("Educations", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.EmergencyContact", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyContactId"));

                    b.Property<int>("BaseInformationId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmergencyContactId");

                    b.HasIndex("BaseInformationId");

                    b.ToTable("EmergencyContacts", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.Resume", b =>
                {
                    b.Property<int>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResumeId"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseInformationId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectSupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectSupervisorPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndCooperationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganizationalPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RecivedSalary")
                        .HasColumnType("float");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResumeId");

                    b.HasIndex("BaseInformationId");

                    b.ToTable("Resumes", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.TrainingRecord", b =>
                {
                    b.Property<int>("TrainingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingRecordId"));

                    b.Property<double?>("Average")
                        .HasColumnType("float");

                    b.Property<int>("BaseInformationId")
                        .HasColumnType("int");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationCityId")
                        .HasColumnType("int");

                    b.Property<int?>("EducationGrade")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TrainingRecordId");

                    b.HasIndex("BaseInformationId");

                    b.ToTable("TrainingRecords", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.BaseInfo.Major", "Major")
                        .WithMany("JobApplicants")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicantFile", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", "JobApplicant")
                        .WithMany("JobApplicantFiles")
                        .HasForeignKey("JobApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplicant");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.PersonQuestionnaireQuestion", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaires.PersonnelQuestionnaire", "PersonnelQuestionnaire")
                        .WithMany("PersonQuestionnaireQuestions")
                        .HasForeignKey("PersonnelQuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaires.QuestionnaireQuestion", "QuestionnaireQuestion")
                        .WithMany()
                        .HasForeignKey("QuestionnaireQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonnelQuestionnaire");

                    b.Navigation("QuestionnaireQuestion");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.PersonnelQuestionnaire", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaires.Questionnaire", "Questionnaire")
                        .WithMany("PersonnelQuestionnaires")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.QuestionnaireQuestion", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaires.Question", "Question")
                        .WithMany("QuestionnaireQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaires.Questionnaire", "Questionnaire")
                        .WithMany("QuestionnaireQuestions")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.Education", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.WorkWthUs.BaseInformation", null)
                        .WithMany("Educations")
                        .HasForeignKey("BaseInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.EmergencyContact", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.WorkWthUs.BaseInformation", "BaseInformation")
                        .WithMany()
                        .HasForeignKey("BaseInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseInformation");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.Resume", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.WorkWthUs.BaseInformation", "BaseInformation")
                        .WithMany("Resumes")
                        .HasForeignKey("BaseInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseInformation");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.TrainingRecord", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.WorkWthUs.BaseInformation", "BaseInformation")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("BaseInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseInformation");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.BaseInfo.Major", b =>
                {
                    b.Navigation("JobApplicants");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", b =>
                {
                    b.Navigation("JobApplicantFiles");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.PersonnelQuestionnaire", b =>
                {
                    b.Navigation("PersonQuestionnaireQuestions");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.Question", b =>
                {
                    b.Navigation("QuestionnaireQuestions");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaires.Questionnaire", b =>
                {
                    b.Navigation("PersonnelQuestionnaires");

                    b.Navigation("QuestionnaireQuestions");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.WorkWthUs.BaseInformation", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Resumes");

                    b.Navigation("TrainingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
