// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teram.HR.Module.Recruitment.Entities.DbContext;

#nullable disable

namespace Teram.HR.Module.Recruitment.Migrations
{
    [DbContext(typeof(HRContext))]
    [Migration("20231031064834_AddIsActiveToQuestions")]
    partial class AddIsActiveToQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.BaseInfo.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MajorId");

                    b.ToTable("Majors", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", b =>
                {
                    b.Property<int>("JobApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificateNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BirthCertificateSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenderType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("decimal(18,15)");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobApplicantId");

                    b.HasIndex("MajorId");

                    b.HasIndex("NationalCode", "Email")
                        .IsUnique();

                    b.ToTable("JobApplicants", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicantFile", b =>
                {
                    b.Property<int>("JobApplicantFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicantFileId"));

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobApplicantId")
                        .HasColumnType("int");

                    b.HasKey("JobApplicantFileId");

                    b.HasIndex("JobApplicantId");

                    b.ToTable("JobApplicantFiles", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.PersonQuestionnaireQuestion", b =>
                {
                    b.Property<int>("PersonQuestionnaireQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonQuestionnaireQuestionId"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionnaireQuestionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonQuestionnaireQuestionId");

                    b.HasIndex("QuestionnaireQuestionId");

                    b.ToTable("PersonQuestionnaireQuestions", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.Questionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionnaireId");

                    b.ToTable("Questionnaires", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.QuestionnaireQuestion", b =>
                {
                    b.Property<int>("QuestionnaireQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionnaireQuestionId"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int");

                    b.HasKey("QuestionnaireQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireQuestions", "HR");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.BaseInfo.Major", "Major")
                        .WithMany("JobApplicants")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicantFile", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", "JobApplicant")
                        .WithMany("JobApplicantFiles")
                        .HasForeignKey("JobApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplicant");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.PersonQuestionnaireQuestion", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaire.QuestionnaireQuestion", "QuestionnaireQuestion")
                        .WithMany()
                        .HasForeignKey("QuestionnaireQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionnaireQuestion");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.QuestionnaireQuestion", b =>
                {
                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaire.Question", "Question")
                        .WithMany("QuestionnaireQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teram.HR.Module.Recruitment.Entities.Questionaire.Questionnaire", "Questionnaire")
                        .WithMany("QuestionnaireQuestions")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.BaseInfo.Major", b =>
                {
                    b.Navigation("JobApplicants");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.JobApplicants.JobApplicant", b =>
                {
                    b.Navigation("JobApplicantFiles");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.Question", b =>
                {
                    b.Navigation("QuestionnaireQuestions");
                });

            modelBuilder.Entity("Teram.HR.Module.Recruitment.Entities.Questionaire.Questionnaire", b =>
                {
                    b.Navigation("QuestionnaireQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
