// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teram.HR.Module.Assets.Entities.DbContext;

#nullable disable

namespace Teram.HR.Module.Assets.Migrations
{
    [DbContext(typeof(AssetContext))]
    [Migration("20231113123517_AddPersonnelCodeToAsset")]
    partial class AddPersonnelCodeToAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teram.HR.Module.Assets.Entities.RahkaranAsset", b =>
                {
                    b.Property<int>("RahkaranAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RahkaranAssetId"));

                    b.Property<long>("AssetID")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Collector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepreciatedMethodTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaqueNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettlementPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilizationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UtilizeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RahkaranAssetId");

                    b.ToTable("RahkaranAssets", "Rahkaran");
                });
#pragma warning restore 612, 618
        }
    }
}
