// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teram.HR.Module.OC.Entities;

#nullable disable

namespace Teram.HR.Module.OC.Migrations
{
    [DbContext(typeof(OCDbContext))]
    partial class OCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teram.HR.Module.OC.Entities.OrganizationChart", b =>
                {
                    b.Property<int>("OrganizationChartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationChartId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentOrganizationChartId")
                        .HasColumnType("int");

                    b.Property<string>("PersonnelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationChartId");

                    b.HasIndex("ParentOrganizationChartId");

                    b.HasIndex("PositionId");

                    b.ToTable("OrganizationChart", "OC");
                });

            modelBuilder.Entity("Teram.HR.Module.OC.Entities.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Position", "OC");
                });

            modelBuilder.Entity("Teram.HR.Module.OC.Entities.OrganizationChart", b =>
                {
                    b.HasOne("Teram.HR.Module.OC.Entities.OrganizationChart", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentOrganizationChartId");

                    b.HasOne("Teram.HR.Module.OC.Entities.Position", "Position")
                        .WithMany("OrganizationCharts")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Teram.HR.Module.OC.Entities.OrganizationChart", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Teram.HR.Module.OC.Entities.Position", b =>
                {
                    b.Navigation("OrganizationCharts");
                });
#pragma warning restore 612, 618
        }
    }
}
