using System;
using System.Collections.Generic;

namespace Teram.Module.Authentication
{
    /*
        // http://www.jstree.com/
        // Expected format of the node (there are no required fields)
        {
          id          : "string" // will be autogenerated if omitted
          text        : "string" // node text
          icon        : "string" // string for custom
          state       : {
            opened    : boolean  // is the node open
            disabled  : boolean  // is the node disabled
            selected  : boolean  // is the node selected
          },
          children    : []  // array of strings or objects
          li_attr     : {}  // attributes for the generated LI node
          a_attr      : {}  // attributes for the generated A node
        }      
     */

    public class JsTreeNode
    {
        public Guid Key { set; get; } 
        public int Id { set; get; } // نام اين خواص بايد با مستندات هماهنگ باشد
        public string Text { set; get; }
        public string Icon { set; get; }
        public JsTreeNodeState State { set; get; }
        public List<JsTreeNode> Children { set; get; }
        public JsTreeNodeLiAttributes Li_attr { set; get; }
        public JsTreeNodeAAttributes A_attr { set; get; }

        public JsTreeNode()
        {
            State = new JsTreeNodeState();
            Children = new List<JsTreeNode>();
            Li_attr = new JsTreeNodeLiAttributes();
            A_attr = new JsTreeNodeAAttributes();
        }
    }

    public class JsTreeNodeAAttributes
    {
        // به هر تعداد و نام اختياري مي‌توان خاصيت تعريف كرد
        public string Class { set; get; }
        public string Path { set; get; }
        public string ParentName { set; get; }
    }



    public class JsTreeNodeLiAttributes
    {
        // به هر تعداد و نام اختياري مي‌توان خاصيت تعريف كرد
        public string data { set; get; }
    }

    public class JsTreeNodeState
    {
        public bool Opened { set; get; }
        public bool Disabled { set; get; }
        public bool Selected { set; get; }
        public bool Checked { get; set; }
        public string Data { get; set; }

        public JsTreeNodeState()
        {
            Opened = true;
        }
    }
}