// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teram.IT.Module.BackupManagement.Entities;

#nullable disable

namespace Teram.IT.Module.BackupManagement.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    [Migration("20240130115901_ChangeTypeOfSourceAndDestinationData")]
    partial class ChangeTypeOfSourceAndDestinationData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teram.IT.Module.BackupManagement.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.ToTable("Applications", "BK");
                });

            modelBuilder.Entity("Teram.IT.Module.BackupManagement.Entities.ServerPath", b =>
                {
                    b.Property<int>("ServerPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerPathId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerPathId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ServerPaths", "BK");
                });

            modelBuilder.Entity("Teram.IT.Module.BackupManagement.Entities.ServerPath", b =>
                {
                    b.HasOne("Teram.IT.Module.BackupManagement.Entities.Application", "Application")
                        .WithMany("ServerPaths")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Teram.IT.Module.BackupManagement.Entities.Application", b =>
                {
                    b.Navigation("ServerPaths");
                });
#pragma warning restore 612, 618
        }
    }
}
